# Generated by Django 4.2.16 on 2024-10-08 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderNum', models.IntegerField(unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('Bought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.prodmodel')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.siteuser')),
            ],
        ),
    ]
