# Generated by Django 4.2.16 on 2024-10-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='OrderNum',
            field=models.IntegerField(),
        ),
    ]
