# Generated by Django 4.2.16 on 2024-10-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0005_alter_orders_ordernum'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
